FROM node:20-alpine

WORKDIR /app

# Dependencies
COPY frontend/package*.json ./
RUN npm ci --legacy-peer-deps

# Frontend code
COPY frontend/ .

# Build
RUN npm run build

# Port
EXPOSE 3000

# Start
CMD ["npm", "start"]
